protected/models/Messages.php
<?php

/**
 * This is the model class for table "messages".
 *
 * The followings are the available columns in table 'messages':
 * @property integer $ID
 * @property integer $userid
 * @property integer $event_id
 * @property string $mtitle
 * @property string $mdescription
 * @property integer $mread
 * @property string $mtype
 * @property integer $mto
 * @property integer $mfrom
 * @property string $createdat
 *
 * The followings are the available model relations:
 * @property Users $user
 * @property Events $event
 */
class Messages extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'messages';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('userid, event_id, mtitle, mdescription, mto, mfrom', 'required'),
			array('userid, event_id, mread, mto, mfrom', 'numerical', 'integerOnly'=>true),
			array('mtitle', 'length', 'max'=>350),
			array('mtype', 'length', 'max'=>150),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('ID, userid, event_id, mtitle, mdescription, mread, mtype, mto, mfrom, createdat', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'user' => array(self::BELONGS_TO, 'Users', 'userid'),
			'event' => array(self::BELONGS_TO, 'Events', 'event_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'ID' => 'ID',
			'userid' => 'Userid',
			'event_id' => 'Event',
			'mtitle' => 'Mtitle',
			'mdescription' => 'Mdescription',
			'mread' => 'Mread',
			'mtype' => 'Mtype',
			'mto' => 'Mto',
			'mfrom' => 'Mfrom',
			'createdat' => 'Createdat',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('ID',$this->ID);
		$criteria->compare('userid',$this->userid);
		$criteria->compare('event_id',$this->event_id);
		$criteria->compare('mtitle',$this->mtitle,true);
		$criteria->compare('mdescription',$this->mdescription,true);
		$criteria->compare('mread',$this->mread);
		$criteria->compare('mtype',$this->mtype,true);
		$criteria->compare('mto',$this->mto);
		$criteria->compare('mfrom',$this->mfrom);
		$criteria->compare('createdat',$this->createdat,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Messages the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/MessagesController.php
<?php

class MessagesController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			//'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			//array('allow',  // allow all users to perform 'index' and 'view' actions
				//'actions'=>array(),
				//'users'=>array('*'),
			//),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','all','unread','outbox','view'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('delete','admin','update','index'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	

	// All Inbox Messages
	public function actionAll()
	{
		$userID = Yii::app()->user->id;
		$model = Messages::model()->findAllByAttributes(array('mto'=>$userID));
		// echo "<pre>";
		// print_r($model);exit;
		$this->render('all',array(
			'model'=>$model,
		));
	}

	// All Unread Messages
	public function actionUnread()
	{
		$userID = Yii::app()->user->id;
		$model = Messages::model()->findAllByAttributes(array('mto'=>$userID, 'mread'=>0));

		$this->render('unread',array(
			'model'=>$model,
		));
	}

	// All Outbox Messages
	public function actionOutbox()
	{
		$userID = Yii::app()->user->id;		
		$model = Messages::model()->findAllByAttributes(array('mfrom'=>$userID));

		$this->render('outbox',array(
			'model'=>$model,
		));
	}
	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$userID=Yii::app()->user->id;
		// Get a message where MessageToID is equal to AutheticatedUserID
		$model=Messages::model()->findByAttributes(array('ID'=>$id, 'mto'=>$userID));

		if (!empty($model)) {

			$model->mread = 1;
			$type = $model->mtype;

			if (!empty($type) AND $type != 'forward,received') {
				$model->mtype = $type.',received';
				$model->save();
				$this->render('view',array(
					'model'=>$this->loadModel($id),
				));
			}
		}
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
		
		
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Messages;

		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);

		$senderId = Yii::app()->user->id;
		// print_r($senderId);exit;
		if(isset($_POST['Messages']))
		{
			$model->attributes=$_POST['Messages'];

			$model->mfrom = $senderId;
			$model->userid = $_POST['userid'];
			$model->event_id = $_POST['event_id'];
			$model->mto = $_POST['mto'];
			$model->mtype = 'forward'; // When message sent to another side
			
			if($model->save()){
				Yii::app()->user->setFlash('saved', 'Message has been sent!');
				$this->redirect(array('all','id'=>$model->ID));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}


	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Messages']))
		{
			$model->attributes=$_POST['Messages'];
			$model->mtype = 'forward'; // When message sent to another side
			$model->mread = 0;
			if($model->save()){
				$this->redirect(array('index','id'=>$model->ID));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Messages');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Messages('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Messages']))
			$model->attributes=$_GET['Messages'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Messages the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Messages::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Messages $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='messages-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/messages/_form.php
<?php
/* @var $this MessagesController */
/* @var $model Messages */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'messages-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<!-- <div class="row">
		<?php //echo $form->labelEx($model,'user id'); ?>
		<?php //echo $form->textField($model,'userid'); ?>
		<?php //echo $form->error($model,'userid'); ?>
	</div> -->

	<!-- <div class="row">
		<?php //echo $form->labelEx($model,'event id'); ?>
		<?php //echo $form->textField($model,'event_id'); ?>
		<?php //echo $form->error($model,'event_id'); ?>
	</div> -->
	
	<input type="hidden" name="userid" value="1">
	<input type="hidden" name="event_id" value="7">
	<input type="hidden" name="mto" value="2">

	<div class="row">
		<?php echo $form->labelEx($model,'m title'); ?>
		<?php echo $form->textField($model,'mtitle',array('size'=>60,'maxlength'=>350)); ?>
		<?php echo $form->error($model,'mtitle'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'m description'); ?>
		<?php echo $form->textArea($model,'mdescription',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'mdescription'); ?>
	</div>

	<!-- <div class="row">
		<?php //echo $form->labelEx($model,'m read'); ?>
		<?php //echo $form->textField($model,'mread'); ?>
		<?php //echo $form->error($model,'mread'); ?>
	</div> -->

	<!-- <div class="row">
		<?php //echo $form->labelEx($model,'m type'); ?>
		<?php //echo $form->textField($model,'mtype',array('size'=>60,'maxlength'=>150)); ?>
		<?php //echo $form->error($model,'mtype'); ?>
	</div> -->
	
	<!-- <div class="row">
		<?php // echo $form->labelEx($model,'m to'); ?>
		<?php // echo $form->textField($model,'mto'); ?>
		<?php // echo $form->error($model,'mto'); ?>
	</div> -->

	<!-- <div class="row">
		<?php //echo $form->labelEx($model,'m from'); ?>
		<?php //echo $form->textField($model,'mfrom'); ?>
		<?php //echo $form->error($model,'mfrom'); ?>
	</div> -->

	<!-- <div class="row">
		<?php //echo $form->labelEx($model,'createdat'); ?>
		<?php //echo $form->textField($model,'createdat'); ?>
		<?php //echo $form->error($model,'createdat'); ?>
	</div> -->

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/messages/_search.php
<?php
/* @var $this MessagesController */
/* @var $model Messages */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'ID'); ?>
		<?php echo $form->textField($model,'ID'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'userid'); ?>
		<?php echo $form->textField($model,'userid'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'event_id'); ?>
		<?php echo $form->textField($model,'event_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'mtitle'); ?>
		<?php echo $form->textField($model,'mtitle',array('size'=>60,'maxlength'=>350)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'mdescription'); ?>
		<?php echo $form->textArea($model,'mdescription',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'mread'); ?>
		<?php echo $form->textField($model,'mread'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'mtype'); ?>
		<?php echo $form->textField($model,'mtype',array('size'=>60,'maxlength'=>150)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'mto'); ?>
		<?php echo $form->textField($model,'mto'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'mfrom'); ?>
		<?php echo $form->textField($model,'mfrom'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'createdat'); ?>
		<?php echo $form->textField($model,'createdat'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/messages/_view.php
<?php
/* @var $this MessagesController */
/* @var $data Messages */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('ID')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->ID), array('view', 'id'=>$data->ID)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('userid')); ?>:</b>
	<?php echo CHtml::encode($data->userid); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('event_id')); ?>:</b>
	<?php echo CHtml::encode($data->event_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('mtitle')); ?>:</b>
	<?php echo CHtml::encode($data->mtitle); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('mdescription')); ?>:</b>
	<?php echo CHtml::encode($data->mdescription); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('mread')); ?>:</b>
	<?php echo CHtml::encode($data->mread); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('mtype')); ?>:</b>
	<?php echo CHtml::encode($data->mtype); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('mto')); ?>:</b>
	<?php echo CHtml::encode($data->mto); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('mfrom')); ?>:</b>
	<?php echo CHtml::encode($data->mfrom); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('createdat')); ?>:</b>
	<?php echo CHtml::encode($data->createdat); ?>
	<br />

	*/ ?>

</div>

protected/views/messages/admin.php
<?php
/* @var $this MessagesController */
/* @var $model Messages */

$this->breadcrumbs=array(
	'Messages'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Messages', 'url'=>array('index')),
	array('label'=>'Create Messages', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#messages-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Messages</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'messages-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'ID',
		'userid',
		'event_id',
		'mtitle',
		'mdescription',
		'mread',
		/*
		'mtype',
		'mto',
		'mfrom',
		'createdat',
		*/
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/messages/all.php
<?php
/* @var $this MessagesController */
/* @var $model Messages */
// exit('okkkk');
	$this->breadcrumbs=array(
		'Messages'=>array('index'),
		'Manage',
	);

	$this->menu=array(
		array('label'=>'List Messages', 'url'=>array('index')),
		array('label'=>'Create Messages', 'url'=>array('create')),
		// custom links
		array('label'=>'All Messages', 'url'=>array('all')),
		array('label'=>'Unread Messages', 'url'=>array('unread')),
		array('label'=>'Outbox Messages', 'url'=>array('outbox')),
	);

	Yii::app()->clientScript->registerScript('search', "
		$('.search-button').click(function(){
			$('.search-form').toggle();
			return false;
		});
		$('.search-form form').submit(function(){
			$('#messages-grid').yiiGridView('update', {
				data: $(this).serialize()
			});
			return false;
		});
	");

?>

<h1>Inbox Messages</h1>

<!-- Flash messages -->
<?php
	foreach (Yii::app()->user->getFlashes() as $type => $flash) {
		echo "<div class='{$type}' style='color:green;'>{$flash}</div>";
	}
?>
<br><br>

<?php if(!empty($model)){?>

<div class="search-form" style="display:none">
	<?php 
		// $this->renderPartial('_search',array(
		// 	'model'=>$model,
		// )); 
	?>
</div><!-- search-form -->

<ul class="list-group">
	<?php foreach ($model as $value) {?>
		<?php if ($value->mread == 1) { ?>
			<li class="list-group-item list-group-item-success" style="background: #f5f5f5;">
				<?php echo $value['mtitle']; ?>
				&nbsp;&nbsp;&nbsp;
				<span class="pull-right">
					<span>
						<?php echo $value['createdat']; ?>
					</span>
					<?php echo CHtml::link('View', array('messages/view', 'id'=>$value->ID), array('class'=>'btn btn-warning btn-xs')); ?>
				</span>
			</li>
		<?php } else{ ?>
			<li class="list-group-item">
				<?php echo $value['mtitle']; ?>
				&nbsp;&nbsp;&nbsp;
				<span class="pull-right">
					<span>
						<?php echo $value['createdat']; ?>
					</span>
					<?php echo CHtml::link('View', array('messages/view', 'id'=>$value->ID), array('class'=>'btn btn-warning btn-xs')); ?>
				</span>
			</li>
		<?php } ?>
	<?php } ?>
</ul>

<?php 
	// $this->widget('zii.widgets.grid.CGridView', array(
	// 	'id'=>'messages-grid',
	// 	'dataProvider'=>$model->search2(),
	// 	//'filter'=>$model,
	// 	'columns'=>array(
	// 		'ID',
	// 		'userid',
	// 		'event_id',
	// 		'mtitle',
	// 		'mdescription',
	// 		'mread',
	// 		/*
	// 		'mtype',
	// 		'mto',
	// 		'mfrom',
	// 		'createdat',
	// 		*/
	// 		array(
	// 			'class'=>'CButtonColumn',
	// 		),
	// 	),
	// ));

}else{
	echo '<div class="well well-small">No Inbox Messages.</div>';
}
?>

protected/views/messages/create.php
<?php
/* @var $this MessagesController */
/* @var $model Messages */

$this->breadcrumbs=array(
	'Messages'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Messages', 'url'=>array('index')),
	array('label'=>'Manage Messages', 'url'=>array('admin')),
	// custom links
	array('label'=>'All Messages', 'url'=>array('all')),
	array('label'=>'Unread Messages', 'url'=>array('unread')),
	array('label'=>'Outbox Messages', 'url'=>array('outbox')),
);
?>

<h1>Create Messages</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/messages/index.php
<?php
/* @var $this MessagesController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Messages',
);

$this->menu=array(
	array('label'=>'Create Messages', 'url'=>array('create')),
	array('label'=>'Manage Messages', 'url'=>array('admin')),
);
?>

<h1>Messages</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/messages/outbox.php
<?php
	/* @var $this MessagesController */
	/* @var $model Messages */

	$this->breadcrumbs=array(
		'Messages'=>array('index'),
		'Manage',
	);

	$this->menu=array(
		array('label'=>'List Messages', 'url'=>array('index')),
		array('label'=>'Create Messages', 'url'=>array('create')),
		array('label'=>'All Messages', 'url'=>array('all')),
		array('label'=>'Unread Messages', 'url'=>array('unread')),
		array('label'=>'Outbox Messages', 'url'=>array('outbox')),
	);

	Yii::app()->clientScript->registerScript('search', "
		$('.search-button').click(function(){
			$('.search-form').toggle();
			return false;
		});
		$('.search-form form').submit(function(){
			$('#messages-grid').yiiGridView('update', {
				data: $(this).serialize()
			});
			return false;
		});
	");
?>

<h1>Outbox Messages</h1>


<?php if(!empty($model)){?>

<div class="search-form" style="display:none">
	<?php 
		// $this->renderPartial('_search',array(
		// 	'model'=>$model,
		//)); 
	?>
</div><!-- search-form -->

<ul class="list-group">
	<?php foreach ($model as $value) {?>
		<li class="list-group-item">
			<?php echo $value['mtitle']; ?>
			&nbsp;&nbsp;&nbsp;
			<span class="pull-right">
				<span>
					<?php echo $value['createdat']; ?>
				</span>
				<?php echo CHtml::link('View', array('messages/view', 'id'=>$value->ID), array('class'=>'btn btn-warning btn-xs')); ?>
			</span>
		</li>
	<?php } ?>
</ul>


<?php 
	// $this->widget('zii.widgets.grid.CGridView', array(
	// 	'id'=>'messages-grid',
	// 	'dataProvider'=>$model->search(),
	// 	'filter'=>$model,
	// 	'columns'=>array(
	// 		'ID',
	// 		'userid',
	// 		'event_id',
	// 		'mtitle',
	// 		'mdescription',
	// 		'mread',
	// 		/*
	// 		'mtype',
	// 		'mto',
	// 		'mfrom',
	// 		'createdat',
	// 		*/
	// 		array(
	// 			'class'=>'CButtonColumn',
	// 		),
	// 	),
	// )); 

}else{
	echo '<div class="well well-small">No Outbox Messages.</div>';
}
?>

protected/views/messages/unread.php
<?php
	/* @var $this MessagesController */
	/* @var $model Messages */

	$this->breadcrumbs=array(
		'Messages'=>array('index'),
		'Manage',
	);

	$this->menu=array(
		array('label'=>'List Messages', 'url'=>array('index')),
		array('label'=>'Create Messages', 'url'=>array('create')),
		array('label'=>'All Messages', 'url'=>array('all')),
		array('label'=>'Unread Messages', 'url'=>array('unread')),
		array('label'=>'Outbox Messages', 'url'=>array('outbox')),
	);

	Yii::app()->clientScript->registerScript('search', "
		$('.search-button').click(function(){
			$('.search-form').toggle();
			return false;
		});
		$('.search-form form').submit(function(){
			$('#messages-grid').yiiGridView('update', {
				data: $(this).serialize()
			});
			return false;
		});
	");
?>

<h1>Unread Messages</h1>


<?php if(!empty($model)){?>

<div class="search-form" style="display:none">
	<?php 
		// $this->renderPartial('_search',array(
		// 	'model'=>$model,
		// )); 
	?>
</div><!-- search-form -->

<ul class="list-group">
	<?php foreach ($model as $value) {?>
		<li class="list-group-item">
			<?php echo $value['mtitle']; ?>
			&nbsp;&nbsp;&nbsp;
			<span class="pull-right">
				<span>
					<?php echo $value['createdat']; ?>
				</span>
				<?php echo CHtml::link('View', array('messages/view', 'id'=>$value->ID), array('class'=>'btn btn-warning btn-xs')); ?>
			</span>
		</li>
	<?php } ?>
</ul>

<?php 
	// $this->widget('zii.widgets.grid.CGridView', array(
	// 	'id'=>'messages-grid',
	// 	'dataProvider'=>$model->search(),
	// 	'filter'=>$model,
	// 	'columns'=>array(
	// 		'ID',
	// 		'userid',
	// 		'event_id',
	// 		'mtitle',
	// 		'mdescription',
	// 		'mread',
	// 		/*
	// 		'mtype',
	// 		'mto',
	// 		'mfrom',
	// 		'createdat',
	// 		*/
	// 		array(
	// 			'class'=>'CButtonColumn',
	// 		),
	// 	),
	// )); 
}else{
	echo '<div class="well well-small">No Unread Messages.</div>';
}
?>

protected/views/messages/update.php
<?php
/* @var $this MessagesController */
/* @var $model Messages */

$this->breadcrumbs=array(
	'Messages'=>array('index'),
	$model->ID=>array('view','id'=>$model->ID),
	'Update',
);

$this->menu=array(
	array('label'=>'List Messages', 'url'=>array('index')),
	array('label'=>'Create Messages', 'url'=>array('create')),
	array('label'=>'View Messages', 'url'=>array('view', 'id'=>$model->ID)),
	array('label'=>'Manage Messages', 'url'=>array('admin')),
);
?>

<h1>Update Messages <?php echo $model->ID; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>